### ISSUE TITLE
FFMpeg install in different dir than ImageMagick

### ISSUE THREAD

**Issue by itsSaad** [ruby-av/paperclip-av-transcoder#15]
My `ImageMagick` is install in `/usr/bin` via yum
and my ffmpeg installed via script is in `/user/local/bin' but Paperclip uses the same `command_path` for both. is there a way we can fix this without moving the installations around.

Thanks

**Comment by owahab** [comment]
`paperclip-av-transcoder` uses the system path defined for ffmpeg. There shouldn't be an issue with `ffmpeg` and `imagemagick` being installed in different `bin` directory.

**Comment by itsSaad** [comment]
Ok. Sorry i didn't realize. Thanks for the help.
