### ISSUE TITLE
Watching video

### ISSUE THREAD

**Issue by ACPK** [ruby-av/paperclip-av-transcoder#18]
Could you add the code for adding the video to a view in the README?

**Comment by owahab** [comment]
Not sure how this would help anyone. There's a lot of ways to do that: Flash and Native HTML5.
Google has lots of examples and codes you can use.

**Comment by ACPK** [comment]
@owahab Didn't know if there was one built into the app - especially for older browsers. Using = video_tag displays the screenshot but was hoping for a player to be built in.

**Comment by dt1973** [comment]
You can always use JS to autoplay with `$('video').play();` whenever the video is visible.
