### ISSUE TITLE
MPEG-4 containers, the moov atom must precede...

### ISSUE THREAD

**Issue by jinge6** [ruby-av/paperclip-av-transcoder#21]
I am converting videos to the MP4 format but struck an issue today when attempting to play those converted videos on Android.

The documentation says that "MPEG-4 containers, the moov atom must precede any mdat atoms, but must succeed the ftyp atom."

Is there a setting or the like I should be passing to the transcoder that will achieve the above?

**Comment by owahab** [comment]
Support for qtfaststart has been moved from paperclip-ffmpeg (now paperclip-av-transcoder) to its own gem: https://github.com/ruby-av/paperclip-av-qtfaststart
Still not released by you may use it from source and report bugs there.
