### ISSUE TITLE
Generate multiple thumbnails from video

### ISSUE THREAD

**Issue by dashingd** [ruby-av/paperclip-av-transcoder#25]
Greetings,
I'm trying to find a way to generate multiple thumbnails from uploaded video. After lot of searching i've found a way but it's pure ffmpeg command.
```
ffmpeg -ss number_of_thumb * (total_video/number_of_thumb)  -i video_file  -vframes 1 -s 320x240 thumb_%03d.jpg 
```
This is the url where i find this code: [Debuggable](http://debuggable.com/posts/FFMPEG_multiple_thumbnails:4aded79c-6744-4bc1-b30e-59bccbdd56cb)
please somebody help me to generate this command to paperclip way or tell me how can i generate multiple thumbnails using paperclip-av-transcoder!

Thank you in advance.

Regards,
Arif

**Comment by attenzione** [comment]
You can define multiple styles for paperclip attachment with different ```time:``` option

**Comment by attenzione** [comment]
```
# app/models/user.rb
class User < ActiveRecord::Base
  has_attached_file :avatar, :styles => {
    medium: { geometry: "640x480", format: 'flv' },
    thumb_10: { geometry: "100x100#", format: 'jpg', time: 10 }
    thumb_20: { geometry: "100x100#", format: 'jpg', time: 20 }
  }, :processors => [:transcoder]
end
```
