### ISSUE TITLE
Unable to detect any supported library

### ISSUE THREAD

**Issue by Pagwebchamba** [ruby-av/paperclip-av-transcoder#27]
[AV] Running command: if command -v avprobe 2>/dev/null; then echo "true"; else echo "false"; fi
[AV] Running command: if command -v ffmpeg 2>/dev/null; then echo "true"; else echo "false"; fi
   (0.2ms)  ROLLBACK
Unable to detect any supported library
Redirected to http://localhost:3000/ssdd/edit
Completed 302 Found in 771ms (ActiveRecord: 0.6ms)

i have compile ffmpeg with this source https://trac.ffmpeg.org/wiki/CompilationGuide/Ubuntu

**Comment by owahab** [comment]
You need to make sure ffmpeg path is in the global `$PATH`. The error you're getting means that when Ruby process tried to find a command named `ffmpeg` or `avprobe`, none of them was in the `$PATH` defined for the process or the global `$PATH`.

**Comment by Pagwebchamba** [comment]
ffmpeg have routes on ~/bin  
have ffmpeg  ffplay  ffprobe  ffserver  x264

have idea?

**Comment by Pagwebchamba** [comment]
need install on /usr/local/bin?

**Comment by Pagwebchamba** [comment]
or how to set $PATH to ~/bin on rails gem?

**Comment by owahab** [comment]
Google to the rescue: http://unix.stackexchange.com/questions/94495/globally-change-path-for-all-users-even-in-cron

**Comment by joshuapinter** [comment]
Just a quick note, in my case I didn't even have ffmpeg installed on my Mac dev machine so I had to install via Homebrew: 

```bash
brew install ffmpeg
```

You'll have to install ffmpeg on your server as well and make sure it's in the $PATH so paperclip-av-transcoder can access it correctly.
