### ISSUE TITLE
uninitialized constant Paperclip::Processor

### ISSUE THREAD

**Issue by sachinkamath** [ruby-av/paperclip-av-transcoder#29]
I am getting the following error after starting the server : 

/home/sachin/.rvm/gems/ruby-1.9.3-p551/gems/paperclip-av-transcoder-0.6.4/lib/paperclip/paperclip_processors/transcoder.rb:2:in `<module:Paperclip>': uninitialized constant Paperclip::Processor (NameError)

What am i doing wrong?

**Comment by owahab** [comment]
What's your Paperclip version?

**Comment by akhil211** [comment]
Hi I am having the same issue. Earlier my paperclip version was 4.3.0 but I changed it to 4.2.0 after suggestion but with no luck.

**Comment by sachinkamath** [comment]
Hi, 
I got around this by doing clean install of rvm along with the suggested devise and rails version.

**Comment by jancuk** [comment]
put gem 'paperclip' above gem 'paperclip-av-transcoder' ?

**Comment by akhil211** [comment]
Yes it worked. Putting paperclip gem above paperclip-av-transcoder resolved the issue. Thanks
