### ISSUE TITLE
Process video in background job

### ISSUE THREAD

**Issue by ACPK** [ruby-av/paperclip-av-transcoder#30]
When uploading a large video, the page times out.

**Comment by owahab** [comment]
That's quite common. Transcoding large video files may require few minutes of work and hence your request will timeout. This gem does not attempt to fix this kind of issues.
You can use DelayedPaperclip gem to process your video transcoding in the background.
Check it out: https://github.com/jrgifford/delayed_paperclip/

**Comment by ACPK** [comment]
@owahab I am using /jrgifford/delayed_paperclip/ and it uploads the video (gives a percentage) but it still seems to be doing something while "updating"  the record. Hence, it still times out even with delayed_paperclip.  Is there something I'm missing so it can save the record?
