### ISSUE TITLE
Can't transcode flv-x files

### ISSUE THREAD

**Issue by lohqua** [ruby-av/paperclip-av-transcoder#48]
> content type discovered from file command: video/x-flv. See documentation to allow this combination.

There seems to be no docs that I can find.

```
has_attached_file :video, path: ":rails_root/private/videos/:video_user_name/:video_library_name/:filename", url: "private/videos/:video_user_name/:video_library_name/:filename", styles: {jv_mp4: {format: 'mp4', streaming: true}, jv_webm: {format: 'webm'}, thumb: {geometry: '640x360#', format: 'png', time: 5}}, processors: [:transcoder, :qtfaststart]
  
validates_attachment :video, presence: true, content_type: {content_type: %w(video/mpeg video/mp4 video/3gpp video/flv video/x-flv video/webm)}, size: {in: 0..90.megabytes}
```
It has no issues with mp4, webm, and 3gpp, other than this gem is not smart enough to know if the uploaded file is either mp4 or webm and will transcode a mp4 to a mp4 for example. But it chokes on flv.

**Comment by owahab** [comment]
The gem is a wrapper for ffmpeg/libav. If FLV files are not being transcoded then you might need to recompile ffmpeg/libav with FLV support. Please check ffmpeg/libav documentation.
