### ISSUE TITLE
Delayed job or job queue

### ISSUE THREAD

**Issue by 0000sir** [ruby-av/paperclip-av-transcoder#57]
Hi, this is exactly what I'm looking for, convert huge video files to smaller ones.

But I found it transcode files on form submit, it's there any delayed job or job queue to do this? that will make the web page more quickly, thanks.

**Comment by attenzione** [comment]
You can use delayed_paperclip (https://github.com/jrgifford/delayed_paperclip/) or this can be implemented by skipping file processing on ActiveModel create and executing ActiveJob after model creation.

**Comment by 0000sir** [comment]
Great! Thank you! Delayed Paperclip works perfectly!
