### ISSUE TITLE
issue with generating video/mp4

### ISSUE THREAD

**Issue by superjustin** [ruby-av/paperclip-av-transcoder#6]
appears to generate fine with paperclip-ffmpeg but issue with paperclip-av-transcoder

**Comment by owahab** [comment]
More details please? Code used in both cases? Anything that can help fix this?

**Comment by superjustin** [comment]
I got it generating the mp4.  But if I change the geometry parameters, the video is not scaling and the thumb is not resizing properly.

**Comment by owahab** [comment]
Closing as being not constructive.
